//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAnimGui {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Properties : global::System.Configuration.ApplicationSettingsBase {
        
        private static Properties defaultInstance = ((Properties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Properties())));
        
        public static Properties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenFolderAfterConvert {
            get {
                return ((bool)(this["OpenFolderAfterConvert"]));
            }
            set {
                this["OpenFolderAfterConvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTxtToBytes {
            get {
                return ((bool)(this["EnableTxtToBytes"]));
            }
            set {
                this["EnableTxtToBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomKsePath {
            get {
                return ((bool)(this["UseCustomKsePath"]));
            }
            set {
                this["UseCustomKsePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomKsePath {
            get {
                return ((string)(this["CustomKsePath"]));
            }
            set {
                this["CustomKsePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoSuccessPopup {
            get {
                return ((bool)(this["NoSuccessPopup"]));
            }
            set {
                this["NoSuccessPopup"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGifExportCompletionNotification {
            get {
                return ((bool)(this["ShowGifExportCompletionNotification"]));
            }
            set {
                this["ShowGifExportCompletionNotification"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GifExportPlaybackSpeed {
            get {
                return ((double)(this["GifExportPlaybackSpeed"]));
            }
            set {
                this["GifExportPlaybackSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public int GifExportWidth {
            get {
                return ((int)(this["GifExportWidth"]));
            }
            set {
                this["GifExportWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public int GifExportHeight {
            get {
                return ((int)(this["GifExportHeight"]));
            }
            set {
                this["GifExportHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GifExportScalingMode {
            get {
                return ((int)(this["GifExportScalingMode"]));
            }
            set {
                this["GifExportScalingMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GifExportOutputDirectory {
            get {
                return ((string)(this["GifExportOutputDirectory"]));
            }
            set {
                this["GifExportOutputDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string PreviewResetViewShortcut {
            get {
                return ((string)(this["PreviewResetViewShortcut"]));
            }
            set {
                this["PreviewResetViewShortcut"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public string PreviewPlayPauseShortcut {
            get {
                return ((string)(this["PreviewPlayPauseShortcut"]));
            }
            set {
                this["PreviewPlayPauseShortcut"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewWheelAnimationSwitch {
            get {
                return ((bool)(this["PreviewWheelAnimationSwitch"]));
            }
            set {
                this["PreviewWheelAnimationSwitch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewAutoPlayAnimation {
            get {
                return ((bool)(this["PreviewAutoPlayAnimation"]));
            }
            set {
                this["PreviewAutoPlayAnimation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewShowOrigin {
            get {
                return ((bool)(this["PreviewShowOrigin"]));
            }
            set {
                this["PreviewShowOrigin"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewShowBounds {
            get {
                return ((bool)(this["PreviewShowBounds"]));
            }
            set {
                this["PreviewShowBounds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewHighlightElement {
            get {
                return ((bool)(this["PreviewHighlightElement"]));
            }
            set {
                this["PreviewHighlightElement"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewDarkBackground {
            get {
                return ((bool)(this["PreviewDarkBackground"]));
            }
            set {
                this["PreviewDarkBackground"] = value;
            }
        }

    }
}
