//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAnimGui {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Properties : global::System.Configuration.ApplicationSettingsBase {
        
        private static Properties defaultInstance = ((Properties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Properties())));
        
        public static Properties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenFolderAfterConvert {
            get {
                return ((bool)(this["OpenFolderAfterConvert"]));
            }
            set {
                this["OpenFolderAfterConvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTxtToBytes {
            get {
                return ((bool)(this["EnableTxtToBytes"]));
            }
            set {
                this["EnableTxtToBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomKsePath {
            get {
                return ((bool)(this["UseCustomKsePath"]));
            }
            set {
                this["UseCustomKsePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomKsePath {
            get {
                return ((string)(this["CustomKsePath"]));
            }
            set {
                this["CustomKsePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoSuccessPopup {
            get {
                return ((bool)(this["NoSuccessPopup"]));
            }
            set {
                this["NoSuccessPopup"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteOniResources {
            get {
                return ((string)(this["FavoriteOniResources"]));
            }
            set {
                this["FavoriteOniResources"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OniRecentActions {
            get {
                return ((string)(this["OniRecentActions"]));
            }
            set {
                this["OniRecentActions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OniResourceTags {
            get {
                return ((string)(this["OniResourceTags"]));
            }
            set {
                this["OniResourceTags"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OniFilterPresets {
            get {
                return ((string)(this["OniFilterPresets"]));
            }
            set {
                this["OniFilterPresets"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OniCompactView {
            get {
                return ((bool)(this["OniCompactView"]));
            }
            set {
                this["OniCompactView"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OniTableView {
            get {
                return ((bool)(this["OniTableView"]));
            }
            set {
                this["OniTableView"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SourceLabel,TagText,AnimCount,FrameCount,ElementCount")]
        public string OniTableColumns {
            get {
                return ((string)(this["OniTableColumns"]));
            }
            set {
                this["OniTableColumns"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name=420;SourceLabel=74;TagText=140;AnimCount=64;FrameCount=64;ElementCount=64")]
        public string OniTableColumnWidths {
            get {
                return ((string)(this["OniTableColumnWidths"]));
            }
            set {
                this["OniTableColumnWidths"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grouped")]
        public string OniKAnimExportLayout {
            get {
                return ((string)(this["OniKAnimExportLayout"]));
            }
            set {
                this["OniKAnimExportLayout"] = value;
            }
        }
    }
}
